# Generated by Django 5.0.2 on 2024-03-02 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("collects", "0001_initial"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="collect",
            name="author",
            field=models.ForeignKey(
                help_text="Автор группового сбора.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collects_authored",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="collect",
            name="contributors",
            field=models.ManyToManyField(
                help_text="Пользователи, внесшие свой вклад в групповой сбор.",
                related_name="contributions",
                through="payments.Payment",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Участники",
            ),
        ),
    ]
