# Generated by Django 5.0.2 on 2024-02-29 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collects", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="collect",
            name="author",
            field=models.ForeignKey(
                default=1,
                help_text="Автор группового сбора.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collects_authored",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
            preserve_default=False,
        ),
    ]
