# Generated by Django 5.0.2 on 2024-03-01 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collects", "0003_alter_collect_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collect",
            options={
                "ordering": ["-id"],
                "verbose_name": "Групповой сбор",
                "verbose_name_plural": "Групповые сборы",
            },
        ),
    ]
