# Generated by Django 5.0.2 on 2024-03-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collects", "0004_alter_collect_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collect",
            name="title",
            field=models.CharField(
                help_text="Название группового сбора.",
                max_length=255,
                unique=True,
                verbose_name="Название",
            ),
        ),
    ]
